#-Dpol.driver=chrome
#-Dtags=vijay
#-Dpol.base.url=https://ap-frontend-test.uk-1.cf-app.net
#-Dwebdriver.chrome.driver="/Users/vijayapalkayyam/Downloads/chromedriver"

// Defaults
DEFAULT_ENV: TEST2
DEFAULT_BROWSER: chrome

//Environmant Details
DEV_URL: https://dev.branchhub.co.uk/#/
TEST_URL: https://test.branchhub.co.uk/#/
TEST2_URL: https://test2.branchhub.co.uk/#/
INT_URL: https://int.branchhub.co.uk/#/
PROD_URL: https://prod.branchhub.co.uk/#/
PREPROD_URL: https://preprod.branchhub.co.uk/#/
DOCKER_SEVILLE: "http://192.168.0.32:"
HELP_AND_HOW_LOTTERY: https://postofficetest.service-now.com/itportal?id=kb_category&kb_category=5bf65720db49f7445e92f9c41d96193b



  //PostgreSQL
POSTGRESQL_BASE_URL_MESSAGING: jdbc:postgresql://pg-pol-ap-test.postgres.database.azure.com:5432/branchmessaging
TEST_branchmessaging_username: branchmessaging@pg-pol-ap-test
TEST_branchmessaging_password: tmjfhphsuybhsnvyalctieibwpgmvjib

POSTGRESQL_BASE_URL_ORGANIZATION: jdbc:postgresql://pg-pol-ap-test.postgres.database.azure.com:5432/organization
TEST_organization_username: organization@pg-pol-ap-test
TEST_organization_password: ikcjzbdgyhjvsyvdxwhxmmfiijjjecwp

POSTGRESQL_BASE_URL_USERPREFERENCES: jdbc:postgresql://pg-pol-ap-test.postgres.database.azure.com:5432/userpreferences
TEST_userpreferences_username: userpreferences@pg-pol-ap-test
TEST_userpreferences_password: zorwhqifaiphumwuidzrdheeupghhzik

POSTGRESQL_BASE_URL_COINORDER: jdbc:postgresql://pg-pol-ap-test.postgres.database.azure.com:5432/coinorder
TEST_coinorder_username: coinorder@pg-pol-ap-test
TEST_coinorder_password: nufcgurdutxdznimnqisbbzbcxjngowz


POSTGRESQL_BASE_URL_AUTHORISATION: jdbc:postgresql://pg-pol-ap-test.postgres.database.azure.com:5432/authorisation
TEST_authorisation_username: authorisation@pg-pol-ap-test
TEST_authorisation_password: wrtjwzfuyyewqruxkmvzcvykdogxqlrd

  //PostgreSQL TEST2
POSTGRESQL_BASE_URL_MESSAGING2: jdbc:postgresql://pg-pol-ap-test2.postgres.database.azure.com:5432/branchmessaging
TEST2_branchmessaging_username: branchmessaging@pg-pol-ap-test2
TEST2_branchmessaging_password: aextycpaitznwesibocrjzcswfuqbodc

POSTGRESQL_BASE_URL_ORGANIZATION2: jdbc:postgresql://pg-pol-ap-test2.postgres.database.azure.com:5432/organization
TEST2_organization_username: organization@pg-pol-ap-test2
TEST2_organization_password: omiyjhfznomspnnkinlkrnpfncpuuvtr

POSTGRESQL_BASE_URL_USERPREFERENCES2: jdbc:postgresql://pg-pol-ap-test2.postgres.database.azure.com:5432/userpreferences
TEST2_userpreferences_username: userpreferences@pg-pol-ap-test2
TEST2_userpreferences_password: rtmdpbejmjwtwikxwiaxjzedtoamysfv

POSTGRESQL_BASE_URL_COINORDER2: jdbc:postgresql://pg-pol-ap-test2.postgres.database.azure.com:5432/coinorder
TEST2_coinorder_username: coinorder@pg-pol-ap-test2
TEST2_coinorder_password: mnzprsnvxwzveggpyuvuvxicyexvwcdu

POSTGRESQL_BASE_URL_AUTHORISATION2: jdbc:postgresql://pg-pol-ap-test2.postgres.database.azure.com:5432/authorisation
TEST2_authorisation_username: authorisation@pg-pol-ap-test2
TEST2_authorisation_password: aqcvaiviptuhiowcojzsyiufzddvimbc


  //PostgreSQL INT
POSTGRESQL_BASE_URL_MESSAGING_INT: jdbc:postgresql://pg-pol-ap-int.postgres.database.azure.com:5432/branchmessaging
INT_branchmessaging_username: branchmessaging@pg-pol-ap-int
INT_branchmessaging_password: fpgojuqozaxxoyimonedtpftjthiihrp

POSTGRESQL_BASE_URL_ORGANIZATION_INT: jdbc:postgresql://pg-pol-ap-int.postgres.database.azure.com:5432/organization
INT_organization_username: organization@pg-pol-ap-int
INT_organization_password: brqmqlownijbbubivrvtestjomssbocz

POSTGRESQL_BASE_URL_USERPREFERENCES_INT: jdbc:postgresql://pg-pol-ap-int.postgres.database.azure.com:5432/userpreferences
INT_userpreferences_username: userpreferences@pg-pol-ap-int
INT_userpreferences_password: qnellagavdjwlfgjpckfhnzvatwcneqs

POSTGRESQL_BASE_URL_AUTHORISATION_INT: jdbc:postgresql://pg-pol-ap-int.postgres.database.azure.com:5432/authorisation
INT_authorisation_username: authorisation@pg-pol-ap-int
INT_authorisation_password: khchyaewhvuclxsxqdfhpjcqhkmpxtjn

POSTGRESQL_BASE_URL_COINORDER_INT:
INT_coinorder_username:
INT_coinorder_password:

//PostgreSQL DEV
POSTGRESQL_BASE_URL_MESSAGING_DEV: jdbc:postgresql://pg-pol-ap-dev.postgres.database.azure.com:5432/branchmessaging
DEV_branchmessaging_username: branchmessaging@pg-pol-ap-dev
DEV_branchmessaging_password: fkeqnwxctsdwomvixrjvsaidnhmfbjwr

POSTGRESQL_BASE_URL_ORGANIZATION_DEV: jdbc:postgresql://pg-pol-ap-dev.postgres.database.azure.com:5432/organization
DEV_organization_username: organization@pg-pol-ap-dev
DEV_organization_password: ntnfswppgxbaeqjzjlorfeaclxlzjigc


POSTGRESQL_BASE_URL_USERPREFERENCES_DEV: jdbc:postgresql://pg-pol-ap-dev.postgres.database.azure.com:5432/userpreferences
DEV_userpreferences_username: userpreferences@pg-pol-ap-dev
DEV_userpreferences_password: gosfbjcomngpaaraqdhanbliddxhjcjm

POSTGRESQL_BASE_URL_COINORDER_DEV:
DEV_coinorder_username:
DEV_coinorder_password:

//PAGES
#  LoginPage: auth/login
#  MaintenancePage: auth/maintenance
EmailSentPage: auth/emailSent
DeviceRegistrationPage: auth/registerDevice
ITSMLandingPage:
ForgotPasswordPage: auth/forgottenDetails
LoginPage: auth/login
LogoutPage: auth/loggedOut
MaintenancePage: auth/maintenance
HomePage: itincident
BranchPerformancePage: branchPerformance
BatchMessagePage: batchMessages
BranchMessaging: branchMessaging
FaqPage: help-how-to
ConfigurationLandingPage:
ComparingSalesValuesPage: branchPerformance/report/compare/value
ComparingSalesVolumesPage: branchPerformance/report/compare/volume
SettingsPage: settings
ForcedLogoutPage: auth/changesLogin
ManageAndPublishMessagesPage: manageAndPublishMessages
ExpiryInactivity: auth/expired
NewSessionDetected: auth/newSessionDetected
KnowledgeBase: articles
SentMessagePage: sentMessages
ReportingMessagePage: readMessages
OrderCoinsPage: coinOrder
ViewUpdatePage: viewUpdate
RegistrationStep1: register
RegistrationStep2: register/step2
AlreadyRegistered: register/alreadyRegistered
RegistrationOk: register/successful


//SERVICES ENDPOINTS

CUSTOMER_SESSIONS_BY_USER: customerSessionsByUser
CUSTOMER_SESSIONS_BY_TRADING_DATE: customerSessionsByTradingDate
CUSTOMER_SESSIONS_AVERAGE_BASKET_PER_DAY: customerSessionsAverageBasketPerDay
CUSTOMER_SESSIONS_AVERAGE_BASKET: customerSessionsAverageBasket
CUSTOMER_SESSIONS_BY_HOUR: customerSessionsByHour
COUNT_CUSTOMER_SESSIONS_BY_USER: countCustomerSessionsByUser
LOGIN: login
INVALIDATE_BEARER_TOKEN: bss-backend-proxy/auth/development/api/invalidateBearerToken
NOTIFICATIONS: notifications
BEARER: Bearer
NOTIFY: notify
CHECKPOLICY: checkPolicy
POLICIES: policies
BRANCH_BY_USER: branchByUser
AUTHENTICATE: authenticate
DECRYPT_JWE: decryptJwe
DECRYPT: decrypt
CHECK_PASSWORD_POLICY: checkPasswordPolicy
SUBPILLARS: subpillars
PILLARS: pillars
INCOME_REPORTING_GROUPS_BY_CODE: incomeReportingGroupsByCode
INCOME_REPORTING_GROUPS: incomeReportingGroups
PREFERENCES_POID_USER_PREFERENCE: preferences/{poid}/{userPreference}
PREFERENCES_POID: preferences/{poid}
SYSTEM_PREFERENCES: system/preferences
SALES_VOLUMES_VALUES_INC_REP: salesVolumesValuesIncRep
TOTAL_SALES_VOLUMES_VALUES: totalSalesVolumesValues
CALCULATE_INCOMING: calculateIncoming
SALES_BY_USER_VOLUMES_VALUES: salesByUserVolumesValues
FIND_EMPLOYEE_BY_BRANCH_FADCODE: findEmployeeByBranchFADCode
TOTAL_SALES_BY_USER_VOLUMES_VALUES: totalSalesByUserVolumesValues
TOP_XSALES_BY_VOL: topXSalesByVol
TOP_XSALES_BY_VAL: topXSalesByVal
SALES_VOLUMES_VALUES_INC_REP_REAL_TIME: salesVolumesValuesIncRepRealTime

//ENDPOINTS

  //AuthService
Logout: logout
InOtp: inOTP
ResettingPassword: resettingPassword
PasswordReset: passwordReset
InMaintenance: inMaintenance
InMaintenanceOn: inMaintenance/on
FactorAuth: login2FAsetUp
SubmitFirstTimeOtp: submitFirstTimeOTP
ForceLogout: forceLogout
InMaintenanceOff: inMaintenance/off
VisibilityLogout: systemConfigLogout
Login: login
PublicKey: getPublicKey
ChangePassword: eum/v1/changepassword
RandomSecurityQuestion: eum/v1/getkbaforuser
ValidateAnsweredSecurityQuestions: eum/v1/validatekbaanswers
SigningKeys: getsigningkeys
SwaggerApi: doc/pdf
ForgotPassword: eum/v1/forgotpassword
ResetPassword: eum/v1/resetpasswordfp
ResetUserPassword: eum/v1/resetpassword
EumToken: eum/v1/authenticate
GenerateToken: eum/v1/generatetoken
ForgeRockEumUrl: https://internal.ipt.branchuserauthentication.postoffice.co.uk:8444/eum/v1/
ForgeRockTokenUrl: https://internal.ipt.branchuserauthentication.postoffice.co.uk:8444/oidc/v1/
RefreshBearerToken: refreshBearerToken
Bearer: Bearer
Privileges: privileges
ExistToken: oauth/tokenByUser/
RevokeToken: oauth/revoke
RevokeTokenAll: oauth/revokeAll

  //BannerService
Banner: banner

  //BranchMessage
Message: messages
MessageSent: messages/sent
MessageUserPoid: messages/user/{poid}
MessageUnreadMessagesUserPoid: unreadMessages/user/
MessageUserPoidMessageId: messages/user/{poid}/{messageID}
MessageUserPoidPriority: messages/user/{poid}/priority/{priority}
AcknowledgedMessage: messages/{messageID}/{poid}/acknowledged
MessageId: /messages/{messageID}
MessageRead: /messages/{messageID}/{poid}/read

  //ChangePasswordService
EumV1ChangePassowrd: eum/v1/changepassword

// CashManagementService

CoinOrder: /coinorder

//Valid environments
VALID_ENVIRONMENTS: DEV,TEST,TEST2,PREPROD,INT,PROD

  //DEV API END POINTS
DEV_BSS_AUTHENTICATION_ENDPOINT: https://dev.branchhub.co.uk/authentication/api/
DEV_BSS_PRODUCT_CATALOGUE_ENDPOINT: https://dev.branchhub.co.uk/productcatalogue/api/
DEV_BSS_SALES_ENDPOINT: https://dev.branchhub.co.uk/sales/api/
DEV_BSS_CUSTOMER_SESSIONS_ENDPOINT: https://dev.branchhub.co.uk/customersessions/api/
DEV_AP_MESSAGE_QUEUE_ENDPOINT: https://dev.branchhub.co.uk/messagequeue/api/
DEV_AP_USER_PREFERENCES_ENDPOINT: https://dev.branchhub.co.uk/userpreferences/api/
DEV_AP_AUTHORISATION_ENDPOINT: https://dev.branchhub.co.uk/authorisation/api/
DEV_BH_BRANCH_MESSAGING_ENDPOINT: https://dev.branchhub.co.uk/branchmessaging/api/
DEV_BH_BEARER_TOKEN_ENDPOINT: https://dev.branchhub.co.uk/authorisation/oauth/token?grant_type=client_credentials
DEV_BH_BANNER_ENDPOINT: https://dev.branchhub.co.uk/branchbanner/api/
DEV_BH_COIN_ORDERS_ENDPOINT: https://dev.branchhub.co.uk/coinorder/api
  //TEST API END POINTS
TEST_BSS_AUTHENTICATION_ENDPOINT: https://test.branchhub.co.uk/authentication/api/
TEST_AP_PASSWORDPOLICY_ENDPOINT: https://test.branchhub.co.uk/passwordpolicy/api/
TEST_BSS_PRODUCT_CATALOGUE_ENDPOINT:  https://test.branchhub.co.uk/productcatalogue/api/
TEST_BSS_SALES_ENDPOINT: https://test.branchhub.co.uk/sales/api/
TEST_BSS_CUSTOMER_SESSIONS_ENDPOINT: https://test.branchhub.co.uk/customersessions/api/
TEST_AP_MESSAGE_QUEUE_ENDPOINT: https://test.branchhub.co.uk/messagequeue/
TEST_AP_USER_PREFERENCES_ENDPOINT: https://test.branchhub.co.uk/userpreferences/api/
TEST_AP_AUTHORISATION_ENDPOINT: https://test.branchhub.co.uk/authorisation/api/

TEST_BH_BEARER_TOKEN_ENDPOINT: https://test.branchhub.co.uk/authorisation/oauth/token?grant_type=client_credentials
TEST_BH_BRANCH_MESSAGING_ENDPOINT: https://test.branchhub.co.uk/branchmessaging/api/
TEST_BH_BANNER_ENDPOINT: https://test.branchhub.co.uk/branchbanner/api/

TEST_BH_COIN_ORDERS_ENDPOINT: https://test.branchhub.co.uk/coinorder/api

  //TEST2 API END POINTS
TEST2_BSS_AUTHENTICATION_ENDPOINT: https://test2.branchhub.co.uk/authentication/api/
TEST2_AP_PASSWORDPOLICY_ENDPOINT: https://test2.branchhub.co.uk/passwordpolicy/api/
TEST2_BSS_PRODUCT_CATALOGUE_ENDPOINT:  https://test2.branchhub.co.uk/productcatalogue/api/
TEST2_BSS_SALES_ENDPOINT: https://test2.branchhub.co.uk/sales/api/
TEST2_BSS_CUSTOMER_SESSIONS_ENDPOINT: https://test2.branchhub.co.uk/customersessions/api/
TEST2_AP_MESSAGE_QUEUE_ENDPOINT: https://test2.branchhub.co.uk/messagequeue/
TES2_AP_USER_PREFERENCES_ENDPOINT: https://test2.branchhub.co.uk/userpreferences/api/
TEST2_AP_AUTHORISATION_ENDPOINT: https://test2.branchhub.co.uk/authorisation/api/

TEST2_BH_BEARER_TOKEN_ENDPOINT: https://test2.branchhub.co.uk/authorisation/oauth/token?grant_type=client_credentials
TEST2_BH_BRANCH_MESSAGING_ENDPOINT: https://test2.branchhub.co.uk/branchmessaging/api/
TEST2_BH_BANNER_ENDPOINT: https://test2.branchhub.co.uk/branchbanner/api/

TEST2_BH_COIN_ORDERS_ENDPOINT: https://test2.branchhub.co.uk/coinorder/api

  //INT API END POINTS

INT_BH_BEARER_TOKEN_ENDPOINT: https://int.branchhub.co.uk/authorisation/oauth/token?grant_type=client_credentials
INT_BSS_AUTHENTICATION_ENDPOINT: https://int.branchhub.co.uk/authentication/api/
INT_AP_PASSWORDPOLICY_ENDPOINT: https://int.branchhub.co.uk/passwordpolicy/api/
INT_BSS_PRODUCT_CATALOGUE_ENDPOINT:  https://int.branchhub.co.uk/productcatalogue/api/
INT_BSS_SALES_ENDPOINT: https://int.branchhub.co.uk/sales/api/
INT_BSS_CUSTOMER_SESSIONS_ENDPOINT: https://int.branchhub.co.uk/customersessions/api/

INT_AP_MESSAGE_QUEUE_ENDPOINT: https://int.branchhub.co.uk/messagequeue/api/
INT_AP_USER_PREFERENCES_ENDPOINT: https://int.branchhub.co.uk/userpreferences/api/
INT_AP_AUTHORISATION_ENDPOINT: https://int.branchhub.co.uk/authorisation/api/

INT_BH_BRANCH_MESSAGING_ENDPOINT: https://int.branchhub.co.uk/branchmessaging/api/

INT_BH_BANNER_ENDPOINT: https://int.branchhub.co.uk/branchbanner/api/

INT_BH_COIN_ORDERS_ENDPOINT: https://int.branchhub.co.uk/coinorder/api

  //PROD API END POINTS
PROD_BH_BEARER_TOKEN_ENDPOINT: https://prod.branchhub.co.uk/authorisation/oauth/token?grant_type=client_credentials
PROD_BSS_AUTHENTICATION_ENDPOINT: https://prod.branchhub.co.uk/authentication/api/
PROD_BSS_PRODUCT_CATALOGUE_ENDPOINT:  https://prod.branchhub.co.uk/productcatalogue/api/
PROD_AP_PASSWORDPOLICY_ENDPOINT: https://prod.branchhub.co.uk/passwordpolicy/api/
PROD_BSS_SALES_ENDPOINT: https://prod.branchhub.co.uk/sales/api/
PROD_BSS_CUSTOMER_SESSIONS_ENDPOINT: https://prod.branchhub.co.uk/customersessions/api/

PROD_AP_MESSAGE_QUEUE_ENDPOINT: https://prod.branchhub.co.uk/messagequeue/api/
PROD_AP_USER_PREFERENCES_ENDPOINT: https://prod.branchhub.co.uk/userpreferences/api/
PROD_AP_AUTHORISATION_ENDPOINT: https://prod.branchhub.co.uk/authorisation/api/

PROD_BH_BRANCH_MESSAGING_ENDPOINT: https://prod.branchhub.co.uk/branchmessaging/api/

PROD_BH_BANNER_ENDPOINT: https://prod.branchhub.co.uk/branchbanner/api/

PROD_BH_COIN_ORDERS_ENDPOINT: https://prod.branchhub.co.uk/coinorder/api
  //PREPROD API END POINTS
PREPROD_BH_BEARER_TOKEN_ENDPOINT: https://preprod.branchhub.co.uk/authorisation/oauth/token?grant_type=client_credentials
PREPROD_BSS_AUTHENTICATION_ENDPOINT: https://preprod.branchhub.co.uk/authentication/api/
PREPROD_BSS_PRODUCT_CATALOGUE_ENDPOINT:  https://preprod.branchhub.co.uk/productcatalogue/api/
PREPROD_AP_PASSWORDPOLICY_ENDPOINT: https://preprod.branchhub.co.uk/passwordpolicy/api/
PREPROD_BSS_SALES_ENDPOINT: https://preprod.branchhub.co.uk/sales/api/
PREPROD_BSS_CUSTOMER_SESSIONS_ENDPOINT: https://preprod.branchhub.co.uk/customersessions/api/

PREPROD_AP_MESSAGE_QUEUE_ENDPOINT: https://preprod.branchhub.co.uk/messagequeue/api/
PREPROD_AP_USER_PREFERENCES_ENDPOINT: https://preprod.branchhub.co.uk/userpreferences/api/
PREPROD_AP_AUTHORISATION_ENDPOINT: https://preprod.branchhub.co.uk/authorisation/api/

PREPROD_BH_BRANCH_MESSAGING_ENDPOINT: https://preprod.branchhub.co.uk/branchmessaging/api/

PREPROD_BH_BANNER_ENDPOINT: https://preprod.branchhub.co.uk/branchbanner/api/
PREPROD_BH_COIN_ORDERS_ENDPOINT: https://preprod.branchhub.co.uk/coinorder/api

  //DOCKER_SEVILLE
DOCKER_SEVILLE_BSS_AUTHENTICATION_ENDPOINT: https://preprod.branchhub.co.uk/authentication/api/
DOCKER_SEVILLE_BSS_PRODUCT_CATALOGUE_ENDPOINT:  https://preprod.branchhub.co.uk/productcatalogue/api/
DOCKER_SEVILLE_BSS_SALES_ENDPOINT: https://preprod.branchhub.co.uk/sales/api/
DOCKER_SEVILLE_BSS_CUSTOMER_SESSIONS_ENDPOINT: https://preprod.branchhub.co.uk/customersessions/api/

DOCKER_SEVILLE_AP_MESSAGE_QUEUE_ENDPOINT: http://192.168.0.32:9092/api/
DOCKER_SEVILLE_AP_USER_PREFERENCES_ENDPOINT: http://192.168.0.32:9093/api/
DOCKER_SEVILLE_AP_AUTHORISATION_ENDPOINT: http://192.168.0.32:9094/api/

DOCKER_SEVILLE_BH_BRANCH_MESSAGING_ENDPOINT: http://192.168.0.32:9097/api/

DOCKER_SEVILLE_BH_BANNER_ENDPOINT: https://preprod.branchhub.co.uk/branchbanner/api/

  //Development config
bss.automationtests.default.login.username: ZUSF
bss.automationtests.default.login.password: G757JF96ZL85AETW
bss.automationtests.default.login.hashedpassword: 7acc5512160763002523a3b17bc3d4d05ee833a68437d85ac955716ce61b3718

bss.automationtests.userpreferences.url: https://ap-userpreferences-test.uk-1.cf-app.net/api/
bss.automationtests.customersessions.url: https://bss-customersessions-test.uk-1.cf-app.net/api/
authorization.url: https://ap-authorisation-dev.uk-1.cf-app.net
bss.automationtests.product-catalogue.url: https://bss-product-catalogue-test.uk-1.cf-app.net/api/
bss.automationtests.organization.url: https://bss-organization-test.uk-1.cf-app.net/api/
bbs.automationtest.branchmessaging.url: https://bh-branchmessaging-test.uk-1.cf-app.net/api/
bss.automationtests.driver.base.url: https://ap-frontend-test.uk-1.cf-app.net
bss.apigee.url: http://bss-organization-dev.uk-1.cf-app.net/api/
bss.automationtests.sales.url: https://bss-sales-test.uk-1.cf-app.net/api/
ap.apigee.url: https://dev-hss.mycnets.com:10443
bss.automationtests.auth.url: https://bss-auth-test.uk-1.cf-app.net/api/
bss.automationtests.webdriver.remote.url: http://192.168.0.32:4444/wd/hub

bss.app.name: Branch Hub
ap.messagequeue.sessionexpiry.popup.text: Your session will be expired in 20 seconds and you will be logged out of Branch Hub.
ap.messagequeue.maintenance.popup.title: Scheduled Maintenance
ap.messagequeue.userpreferences.popup.text: You will be Logged out of Branch Hub due to a functionality change.
ap.messagequeue.maintenance.popup.text: You will be Logged out of Branch Hub due to a scheduled maintenance.
ap.messagequeue.userpreferences.popup.title: Configuration's change


ap.messagequeue.topic.queue.broadcast: /queue/all/
ap.messagequeue.sessionexpiry.popup.title: Session Timeout
ap.messagequeue.topic.queue.user: /queue/user/

bss.automationtests.tags: @development ~@ignore

swagger.enable: true
spring.jpa.generate-ddl: false
bss.apigee.use: true
bss.automationtests.webdriver.remote.disabled: true

# DRIVER

bss.automationtests.driver: chrome
bss.automationtests.webdriver.remote.driver: chrome

spring.datasource.hikari.minimumIdle: 5
bss.automationtest.maintenance.sleeptime: 20000

ap.security.environment.keystore_password: KEYSTORE_PASSWORD
ap.security.environment.keystore: KEYSTORE

ap.messagequeue.userpreferences.logout.code: 2003
ap.messagequeue.maintenance.popup.code: 1001
ap.messagequeue.userpreferences.popup.code: 1003
ap.messagequeue.maintenance.logout.code: 2001

spring.datasource.hikari.idleTimeout: 30000
bss.app.tradingdate.minimumqueriablemonths: 12
spring.datasource.hikari.maximumPoolSize: 5
spring.datasource.hikari.maxLifetime: 2000000
ap.messagequeue.sessionexpiry.logout.code: 2002
spring.datasource.hikari.connectionTimeout: 30000

ap.security.supportedTLS: TLSv1.2
ap.security.environment.keystore_type: JKS
ap.messagequeue.sessionexpiry.popup.code: 1002



##swagger-ui.html
##Authentication (bss-auth)
#AUTHENTICATION_ENDPOINT : https://bss-auth-%s.uk-1.cf-app.net
#
##Authorisation (ap_authorisation)
#AUTHORISATION_ENDPOINT : https://ap-authorisation-%s.uk-1.cf-app.net
#
##Sales (bss-sales)
#SALES_ENDPOINT : https://bss-sales-%s.uk-1.cf-app.net
#
##Customer Sessions (bss-customersessions)
#CUSTOMER_SESSIONS_ENDPOINT : https://bss-customersessions-%s.uk-1.cf-app.net/
#
##MessageQueue (messagequeu)
#MESSAGE_QUESUE_ENDPOINT: https://ap-messagequeue-%s.uk-1.cf-app.net/
#
##UserDetails Preferences (ap-userpreferences)
#USER_OREFERENCES_ENDPOINT: https://ap-userpreferences-%s.uk-1.cf-app.net/
#
##Product Catalog (bss-product-catalogue)
#PRODUCT_CATALOGUE_ENDPOINT : https://bss-product-catalogue-%s.uk-1.cf-app.net/


logging.level.com.pol.bss = TRACE